version: '3.8'
services:
  db:
    image: postgres
    restart: always
    read_only: true
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: mob123
      POSTGRES_DB: mobexa
    ports:
      - 5432:5432
    volumes:
      - ./var/lib/postgresql/data

